import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Adryann",
      email: "admin@admin.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "Adriana",
      email: "exemple@exemple.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      id: "1",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/caneca.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: "2",
      name: "Adidas Fit Shirt",
      category: "Shirts",
      image: "/images/Mask.jpg",
      price: 100,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: "3",
      name: "Lacoste Free Shirt",
      category: "Shirts",
      image: "/images/oculos-de-grau.jpg",
      price: 220,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
    },
    {
      id: "4",
      name: "Nike Slim Pant",
      category: "Pants",
      image: "/images/oculos-escuro.jpg",
      price: 78,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      id: "5",
      name: "Puma Slim Pant",
      category: "Pants",
      image: "/images/oculos-preto.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: "6",
      name: "Adidas Fit Pant",
      category: "Pants",
      image: "/images/caneca.jpg",
      price: 139,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
  ],
};
export default data;
